### ISSUE TITLE
Not able to add students

### ISSUE THREAD

**Issue by narendrago** [vijaythapa333/django-student-management-system#2]
Shows 'failed to add students' whenever I try to add student

**Comment by bpmaurya** [comment]
yes Here in this code have bug in add student section

**Comment by AkshayGaikwad02** [comment]
Yes sir here is some problem for add a new students...plz can you solve this problem .... I am use this project for educational and now submission date coming so plz can u solve this....

**Comment by AkshayGaikwad02** [comment]
> Shows 'failed to add students' whenever I try to add student

Did you solved this problem???

**Comment by MhdAliHarmalani** [comment]
it is worked with me when I changed course_id to exist one, in models.py file in line 186: 
I changed from 1 to 2 like that:

Students.objects.create(admin=instance, course_id=Courses.objects.get(id=2), session_year_id=SessionYearModel.objects.get(id=1), address="", profile_pic="", gender="")

**Comment by afnanplk** [comment]
> it is worked with me when I changed course_id to exist one, in models.py file in line 186: I changed from 1 to 2 like that:
> 
> Students.objects.create(admin=instance, course_id=Courses.objects.get(id=2), session_year_id=SessionYearModel.objects.get(id=1), address="", profile_pic="", gender="")

how to delete all the students 
i cant delete first two students

**Comment by ahmar-js** [comment]
> how to delete all the students i cant delete first two students

Go to model.py file in **AttendanceReport class**; Change 
` student_id = models.ForeignKey(Students, on_delete=models.DO_NOTHING)
`
 to 
` student_id = models.ForeignKey(Students, on_delete=models.CASCADE)
`

Then again make migrations by `py manage.py makemigrations` and then `py manage.py migrate` 

It will definitely work.

**Comment by efre1m** [comment]
reCAPTCHA is not terminating. can you tell me how to solve or remove the recaptcha
